### PR TITLE
Upgrade nodejs and hapi stack in order to support Apple M1

### LINKED ISSUE #32: Add ARM/Apple M1 support
Any chance you could add ARM/Apple M1 support? Seems the upstream image has arm support already.

### PR DESCRIPTION
**Pull request by pingvinen**
Fixes #32 

This PR represents a huge jump in versions of everything, but as we use very few features of anything, it seems that we have dodged the breaking changes (for the most part).

- `nodejs` jumps from `12.13.x` to `16.13.1`
- `hapi` stack is moved to the "new" `@hapi/xxxx` packages
- `hapi` jumps from `17.5.0` to `20.2.1`

Pretty printing with `pino` has been pulled into its own package, but I have updated the code to continue using pretty printing.

### CODE REVIEW

**Comment by pingvinen** [comment]
I am currently hoping for someone with an Apple M1 to test that this actually works :)

**Comment by jappyjan** [comment]
just tested on M1 Pro.
works :)

**Comment by pingvinen** [comment]
> just tested on M1 Pro. works :)

Cool... Thank you for testing :)

**Comment by pingvinen** [comment]
Just released this as version `0.4.0` ... https://hub.docker.com/r/skarpdev/aws-secrets-manager-emulator/tags

**Pull request merged**
